# Site settings
title: Somi Bae's CV
description: baesomi's CV
favicon: /assets/img/avatar.JPG
baseurl: https://baesomi.github.io
url: https://baesomi.github.io
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Somi Bae
  title: SW Developer
  address: Suwon, South Korea
  email: smbae0249@gmail.com
  link: http://baesomi.github.io
  weibo:
  github: baesomi
  linkedin: somi bae
  twitter: somisom2
  gavatar: /baesomi.github.io/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
  - work1:
    company: LILY in NTU
    location: Pioneer, Singapore
    title: Research Assistent
    started: 2017
    duration: (2017.01 - 2017.02)
    description: I took a part in Global Internship Program.
    I develop the smile treatment mobile application for depressed patients.
    왜 안변하는거야 ㅠㅠ
    
  educationHistory:
    - education1:
      organization: Gachon University
      location: Sungnam, South Korea
      degree: Bachelor
      major: Software
      started: 2014
      duration: (2014 - 2018)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Korea
      proficiency: Native
    - language2:
      name: English
      proficiency: Normal
    - language3:
      name: Japanese
      proficiency: Limit
    - language4:
      name: Chinese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: Java
      percentage: 100%
    - skill2:
      name: Android
      percentage: 100%
    - skill3:
      name: C
      percentage: 80%
    - skill4:
      name: HTML
      percentage: 80%
    - skill5:
      name: Python
      percentage: 30%
